parameters:
    qbitz_dpd.dpdservices.client.class: 'Qbitz\DpdBundle\Dpd\DpdServicesClient'
    qbitz_dpd.appservices.client.class: 'Qbitz\DpdBundle\Dpd\AppServicesClient'
    qbitz_dpd.dpdservices.wsdl:         ~
    qbitz_dpd.appservices.wsdl:         ~
    qbitz_dpd.login:                    ~
    qbitz_dpd.password:                 ~
    qbitz_dpd.fid:                      ~
    qbitz_dpd.dpdservices.output_dir:   ~

services:
    qbitz.dpd.dpdservices:
        class: %qbitz_dpd.dpdservices.client.class%
        arguments:
            - @jms_serializer
            - '%qbitz_dpd.dpdservices.wsdl%'
            - '%qbitz_dpd.login%'
            - '%qbitz_dpd.password%'
            - '%qbitz_dpd.fid%'
            - '%qbitz_dpd.dpdservices.output_dir%'
    qbitz.dpd.appservices:
        class: %qbitz_dpd.appservices.client.class%
        arguments:
            - @jms_serializer
            - '%qbitz_dpd.appservices.wsdl%'
            - '%qbitz_dpd.login%'
            - '%qbitz_dpd.password%'
            - '%qbitz_dpd.fid%'
